apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: argocd-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mateus.lira@qubika.com
    privateKeySecretRef:
      name: argocd-tls
    solvers:
      - http01: 
          ingress: 
            class: nginx
